services:
  admin:
    build:
      context: ../maven_admin
      dockerfile: Dockerfile
    container_name: mavens-admin
    ports:
      - "3001:3001"
    env_file:
      - ../maven_admin/.env
    environment:
      # These override the .env file to ensure containers can talk to each other
      - MONGODB_URI=mongodb://db:27017/mavens
    depends_on:
      - db
    networks:
      - mavens-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mavens-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # These override the .env file to ensure containers can talk to each other
      - MONGODB_URI=mongodb://db:27017/mavens
      - REDIS_URL=redis://cache:6379
    depends_on:
      - db
      - cache
    networks:
      - mavens-network

  db:
    image: mongo:latest
    container_name: mavens-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mavens-network

  cache:
    image: redis:alpine
    container_name: mavens-redis
    ports:
      - "6379:6379"
    networks:
      - mavens-network

networks:
  mavens-network:
    driver: bridge

volumes:
  mongodb_data: